#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www/html
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
