#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

i=0
while [ $i -lt 20 ];
do
  ((i++))
  case $i in
    5)
      echo "bad luck from China"
      ;;
    10)
      echo "bad luck from Japan"
      ;;
    18)
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
  esac
done
